<?php
$sc_style = get_option('scbox_style');
$sc_width = get_option('scbox_width');
$sc_height = get_option('scbox_height');
$sc_trans = get_option('scbox_trans');
$sc_gvari = get_option('scbox_gvari');
$sc_cusvari = get_option('scbox_cusvari');
$sc_globalsc = get_option('scbox_globalsc');
$sc_addhead = get_option('scbox_addhead');
?>

<!--START SIMPLE COLORBOX-->
<link type="text/css" media="screen" rel="stylesheet" href="<?php bloginfo('url'); ?>/wp-content/plugins/simple_cbox/colorbox/<?php if ($sc_style) { echo $sc_style;} else {echo "colorbox.css";} ?>" />
<script type="text/javascript" src="<?php bloginfo('url'); ?>/wp-content/plugins/simple_cbox/colorbox/jquery.min.js"></script>
<script type="text/javascript" src="<?php bloginfo('url'); ?>/wp-content/plugins/simple_cbox/colorbox/jquery.colorbox.js"></script>
<script type="text/javascript">
$(document).ready(function(){
//Colorbox autogenerated rel tag script lines
<?php if($sc_globalsc == 'Enabled') : ?>
<?php if (have_posts()) : while (have_posts()) : the_post(); ?>   
$("a[rel='cbox_<?php the_ID(); ?>']").colorbox({transition:"<?php if ($sc_trans) { echo $sc_trans;} else {echo "none";} ?>", width:"<?php if ($sc_width) { echo $sc_width;} else {echo "70%";} ?>", height:"<?php if ($sc_height) { echo $sc_height;} else {echo "90%";} ?>"<?php if ($sc_gvari) { echo $sc_gvari;} ?>});
<?php endwhile; else: ?>
<?php endif; ?>
<?php endif; ?>

<?php if ($sc_cusvari) { echo $sc_cusvari;} ?>

});
</script>
<!--END SIMPLE COLORBOX-->

<?php echo $sc_addhead; ?>


